### ISSUE TITLE
A request for the raw data

### ISSUE THREAD

**Issue by TOM-ZXian** [AnudeepKonda/BugDetector#1]
It is a good job! But, without the raw data, such as  the tokenFiles, the entropyFiles, the bugFiles and 
 some intermediate files, it is so hard to understand the details, not to mention running the code.
So, please share us more raw data. It will be a great help. Thanks so much!

**Comment by lancersimmons** [comment]
Tom, our data was obtained from a professor. Unfortunately, it's part of their ongoing research and not available for us to share publicly.

**Comment by TOM-ZXian** [comment]
Roger that.
